name: Freeze app with new data

# Controls when the workflow will run
on:
  schedule:
    - cron: '10 8 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: grab python dependencies
        run: python -m pip install Frozen-Flask
      
      # Runs a single command using the runners shell
      - name: Run freezing script
        run: python freeze.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "freezer-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Freezing pages from: ${timestamp}" || exit 0
          git push
