# This is a basic workflow to help you get started with Actions

name: Auto-tweet

# Controls when the workflow wil.l run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: grab python dependencies
        run: python -m pip install tweepy
      
      # Runs a single command using the runners shell
      - name: Run tweeting script
        env: 
          TWEEPY_API_KEY: ${{ secrets.TWEEPY_API_KEY }}
          TWEEPY_API_TOKEN: ${{ secrets.TWEEPY_API_TOKEN }}
          TWEEPY_ACCESS_TOKEN: ${{ secrets.TWEEPY_ACCESS_TOKEN }}
          TWEEPY_ACCESS_TOKEN_SECRET: ${{ secrets.TWEEPY_ACCESS_TOKEN_SECRET }}
        run: python twitter-bot.py
